### ISSUE TITLE
Unable to build with gcc11.3

### ISSUE THREAD

**Issue by Yong-Q** [snurr-group/mofid#36]
gcc/11.3.0/include/c++/11.3.0/x86_64-pc-linux-gnu/bits/c++config.h:732:25: error: missing binary operator before token "("
 #if _GLIBCXX_HAS_BUILTIN(__has_unique_object_representations)

**Comment by KunhuanLiu** [comment]
Hi, we are aware of this issue and may have an updated MOFid with updated libraries and compatible with newest gcc very soon.
